_target_: hydra_plugins.hydra_ray_launcher.ray_aws_launcher.RayAWSLauncher
env_setup:
  pip_packages:
    omegaconf: 2.3.0
    hydra_core: 1.3.2
    ray: 2.32.0
    cloudpickle: 2.2.1
    hydra_ray_launcher: 1.2.1
  commands:
    - curl -L -O "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    - /bin/bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p "$HOME/anaconda3" || true
    - echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bashrc
ray:
  init:
    address: null
  remote: {}
  cluster:
    cluster_name: default
    min_workers: 0
    upscaling_speed: 1.0
    max_workers: 1
#    initial_workers: 0
#    autoscaling_mode: default
#    target_utilization_fraction: 0.8
    idle_timeout_minutes: 5
    docker:
      image: ''
      container_name: ''
      pull_before_run: true
      run_options: []
    provider:
      type: aws
      region: eu-central-1
      availability_zone: eu-central-1a,eu-central-1b
      cache_stopped_nodes: false
      key_pair:
        key_name: hydra-${oc.env:USER,user}
    auth:
      ssh_user: ec2-user
    available_node_types:
      ray.head.default:
        resources: {}
        node_config:
          InstanceType: t3.micro
          ImageId: ami-0346fd83e3383dcb4
      ray.worker.default:
        min_workers: 0
        max_workers: 2
        resources: {}
        node_config:
          InstanceType: t3.micro
          ImageId: ami-0346fd83e3383dcb4
          InstanceMarketOptions:
            MarketType: spot
    head_node_type: ray.head.default
    file_mounts: {}
    initialization_commands: []
    cluster_synced_files: []
    setup_commands: []
    head_setup_commands: []
    worker_setup_commands: []
    head_start_ray_commands:
    - ray stop
    - ulimit -n 65536;ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml
    worker_start_ray_commands:
    - ray stop
    - ulimit -n 65536; ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076
  run_env:
    name: auto
stop_cluster: true
sync_up:
  source_dir: null
  target_dir: null
  include: []
  exclude: []
sync_down:
  source_dir: null
  target_dir: null
  include: []
  exclude: []
logging:
  log_style: auto
  color_mode: auto
  verbosity: 0
create_update_cluster:
  no_restart: false
  restart_only: false
  no_config_cache: false
teardown_cluster:
  workers_only: false
  keep_min_workers: false
